### ISSUE TITLE
Single quotes in localization bundle prevents loading in production

### ISSUE THREAD

**Issue by diceytroop** [onestopjs/gatsby-theme-localization#19]
Hi! Thanks for this plugin, it's been really helpful to me in my current project.

I have located an issue, though. After pushing my site to production, I noticed that on SSR-rendered pages (everything except the root, which always loads the bundle properly), there was a syntax error in console:

Uncaught SyntaxError: unexpected token: identifier

After a little investigation, I realized that the problem was an unescaped single quote within one of the localized .json files. Since the bundle is stringified and then included in the site code using 

`window.GATSBY_THEME_LOCALIZATION_BUNDLE = '<bundle content>'`

, the browser interprets the first single quote/apostrophe as the end of the string. This obviously truncates the string, and generates a syntax error.

My assumption is that this could be reproduced by adding an apostrophe to any string in any of a gatsby-theme-localization site's translation files.

To solve this, I have for now simply moved the plugin folder from node_modules into plugins/ and edited the compiled embedTranslations.js to turn

```
const Component = PreloadNamespacesComponent_1.default({
        resourceBundle: JSON.stringify(resourceBundle)
});
```

into

```
 const Component = PreloadNamespacesComponent_1.default({
        resourceBundle: JSON.stringify(resourceBundle).replace(/'/g, "\\'")
 });
```

I have not spent the time required to make sure that this is the best or only fix, but at least at this point my production site is not blocked. Would love to hear if you have any suggestions or feedback as to a better way to handle this. If there is none, I'd be happy to submit a pull request for the above fix, as well. Cheers!

**Comment by onestopjs** [comment]
Hey, thanks for the feedback! 

Yeah, this is a case which I hadn't thought about. I can't think of a better fix than the one you proposed, so we can go with that if you don't mind. 

Can you submit a PR, please? If you are not available, I will be able to fix it tomorrow and publish a new version, so don't worry if you can't submit a PR right now 🙂

Cheers!

**Comment by diceytroop** [comment]
Awesome, thanks! Submitted a PR. My first!

**Comment by onestopjs** [comment]
Thank you! Closing this issue for now, if any issue occurs again, feel free to reopen!
